repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      exclude: notebooks/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      exclude: notebooks/
      args: [--max-line-length=88]
-   repo: https://github.com/pre-commit/mirrors-mypy
    sha: master
    hooks:
    -   id: mypy
        exclude: notebooks/
