name: AAAAA
finetune: False
min_unk_sub: 5
embed_size: 300
layers: 2
rnn_hidden_size: 256
cell: gru
keep_prob: 0.7
wd: 0.0001
learning_rate: 0.0001
opt: adam
margin: 0.2
attn_size: 10
gradient_clip_val: 5
seed: 42
