name: DEFLT
min_unk_sub: 5
layers: 2
rnn_hidden_size: 512
keep_prob: 0.7
weight_decay: 0.0001
learning_rate: 0.0001
margin: 50
attn_size: 50
attn_heads: 30
frob_norm_pen: 3.0
gradient_clip_val: 5
seed: 42
batch_hard: false
