name: DEFLT
layers: 1
rnn_hidden_size: 512
keep_prob: 0.7
learning_rate: 0.0002
margin: 0.5
attn_size: 50
attn_heads: 30
frob_norm_pen: 1.0
gradient_clip_val: 5
seed: 42
batch_hard: True
use_gor: True